language: php
php:
  # - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  # - hhvm
  - nightly

services:
  - mysql

before_script: 
  - composer install
  - mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret'; GRANT ALL PRIVILEGES ON * . * TO 'homestead'@'localhost'; FLUSH PRIVILEGES;"
  
script: ./vendor/bin/phpunit
